language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO="Django>=3.0"
install:
  - travis_retry pip install -q $DJANGO
  - python setup.py develop
script: python manage.py test rest_framework_word_filter

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="Django>=1.7,<1.8"
  fast_finish: true